"""
export_pdf.py — Export meeting notes to a professional PDF.

Uses fpdf2 (pure Python, no system dependencies).

Setup:
    pip install fpdf2
"""

import logging
from datetime import datetime
from pathlib import Path
from typing import Optional

from core.config import config
from core.transcriber import TranscriptChunk
from core.summarizer import MeetingSummary

logger = logging.getLogger(__name__)


def _safe(text: str) -> str:
    """
    Replace characters that Helvetica (latin-1) cannot encode.
    Covers the most common offenders from NLP output and AI summaries.
    """
    replacements = {
        "\u2022": "-",    # bullet •
        "\u2013": "-",    # en dash -
        "\u2014": "-",    # em dash -
        "\u2018": "'",    # left single quote
        "\u2019": "'",    # right single quote
        "\u201c": '"',    # left double quote
        "\u201d": '"',    # right double quote
        "\u2026": "...",  # ellipsis
        "\u2192": "->",   # arrow
        "\u2713": "OK",   # check mark
        "\u00b7": "-",    # middle dot
        "\u2023": "-",    # triangular bullet
        "\u25cf": "-",    # black circle
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    # Final fallback: drop anything still outside latin-1
    return text.encode("latin-1", errors="ignore").decode("latin-1")


def export_to_pdf(
    session_id: str,
    transcript: list[TranscriptChunk],
    summary: Optional[MeetingSummary],
    output_path: Optional[Path] = None,
    meeting_title: str = "Meeting Notes",
) -> Path:
    """
    Generate a formatted PDF of the meeting notes.
    Returns the path to the created PDF.
    """
    try:
        from fpdf import FPDF
    except ImportError:
        raise RuntimeError("fpdf2 not installed. Run: pip install fpdf2")

    if output_path is None:
        output_path = config.SUMMARY_DIR / f"meeting_notes_{session_id}.pdf"

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Header
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 12, _safe(meeting_title), ln=True, align="C")

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, _safe(f"Session ID: {session_id}   |   Generated: {datetime.now().strftime('%d %b %Y %H:%M')}"), ln=True, align="C")
    pdf.ln(4)

    # Horizontal rule
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    # Summary section
    if summary:
        _section_header(pdf, "Meeting Summary")
        _body_text(pdf, _safe(summary.summary))
        pdf.ln(4)

        if summary.action_items:
            _section_header(pdf, "Action Items", size=13)
            for item in summary.action_items:
                _bullet(pdf, _safe(item))
            pdf.ln(2)

        if summary.key_points:
            _section_header(pdf, "Key Points", size=13)
            for point in summary.key_points:
                _bullet(pdf, _safe(point))
            pdf.ln(2)

        if summary.highlights:
            _section_header(pdf, "Highlights", size=13)
            for h in summary.highlights:
                _highlight_box(pdf, _safe(h))
            pdf.ln(2)

    # Transcript section
    _section_header(pdf, "Full Transcript")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(50, 50, 50)

    for chunk in transcript:
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(80, 80, 150)
        pdf.cell(30, 5, _safe(f"[{chunk.time_label}]"), ln=False)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(60, 60, 60)
        pdf.cell(30, 5, _safe(f"{chunk.speaker}:"), ln=False)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(30, 30, 30)
        pdf.multi_cell(0, 5, _safe(chunk.text))

    # Footer
    pdf.set_y(-15)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 10, _safe(f"Generated by AI Meeting Notes App | {config.APP_NAME}"), align="C")

    pdf.output(str(output_path))
    logger.info(f"PDF exported: {output_path}")
    return output_path


# Helpers

def _section_header(pdf, title: str, size: int = 14) -> None:
    pdf.set_font("Helvetica", "B", size)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 8, _safe(title), ln=True)
    pdf.ln(1)


def _body_text(pdf, text: str) -> None:
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(50, 50, 50)
    pdf.multi_cell(0, 6, text)


def _bullet(pdf, text: str) -> None:
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(6, 6, "-", ln=False)
    pdf.multi_cell(0, 6, text)


def _highlight_box(pdf, text: str) -> None:
    pdf.set_fill_color(245, 245, 200)
    pdf.set_font("Helvetica", "I", 10)
    pdf.set_text_color(60, 60, 60)
    pdf.multi_cell(0, 6, f'  "{text}"', fill=True)
    pdf.ln(1)
